# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    resolvers :
        default:
            web_path: ~

    filter_sets:
        cache: ~
        # the name of the "filter set"
        thumb480x480:
            quality: 75
            filters:
                thumbnail: { size: [480, 480], mode: outbound }
        thumb64x64:
            quality: 60
            filters:
                thumbnail: { size: [64, 64], mode: outbound }
